# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dixitbhavsar01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f5fa93c4d78346d590219f46d7b33718 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_66d7e1fa88b74ace9eeb00fff7f74229 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f5fa93c4d78346d590219f46d7b33718 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dixitbhavsar01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b2431874913c423ca53a0fffc3676b9d }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f5fa93c4d78346d590219f46d7b33718 }}/appsvc/staticsite:${{ github.sha }}'